# Saturn MouseHunter 爬虫服务 HPA 自动扩缩容配置

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saturn-crawler-critical-hpa
  namespace: saturn-mousehunter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saturn-crawler-critical
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # TODO: 添加自定义队列深度指标
  # - type: External
  #   external:
  #     metric:
  #       name: dragonfly_queue_depth
  #       selector:
  #         matchLabels:
  #           queue_name: "crawler_backfill_critical"
  #     target:
  #       type: AverageValue
  #       averageValue: "25"  # 队列超过25个任务时扩容
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5分钟稳定期
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60   # 1分钟稳定期
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saturn-crawler-high-hpa
  namespace: saturn-mousehunter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saturn-crawler-high
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10分钟稳定期，避免频繁缩容
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saturn-crawler-normal-hpa
  namespace: saturn-mousehunter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saturn-crawler-normal
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900  # 15分钟稳定期
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120